// <auto-generated />
namespace TeamTwoBe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Target201904131017421 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Target201904131017421));
        
        string IMigrationMetadata.Id
        {
            get { return "201905200823403_Target-201904131017421"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
